development: &default
  adapter: postgresql
  database: tdd-outside-in_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: tdd-outside-in_test
